#cloud-config
user: dp2-user
password: domotica-prod
chpasswd: { expire: False }
ssh_pwauth: True
package_update: true
packages:
  - qemu-guest-agent
  - iptables-persistent

runcmd:
  - |
      cat <<'EOF' > /etc/netplan/99-config.yaml
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp1s0:
            dhcp4: yes
            routes:
              - to: default
                via: 192.168.122.1
          enp2s0:
            dhcp4: no
            addresses:
              - 10.0.1.10/24
      EOF
  - 'netplan apply'
  - 'echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-forwarding.conf'
  - 'sysctl -p /etc/sysctl.d/99-forwarding.conf'
  - 'iptables -t nat -A POSTROUTING -s 10.0.1.0/24 -o enp2s0 -j MASQUERADE'
  - 'netfilter-persistent save'
